### PR TITLE
Export UMD instead of var library

### PR DESCRIPTION
**Pull request by agjohnson**
This is still usable in the browser, we aren't relying on a global variable anyways, but it's there if needed.

### CODE REVIEW

**Comment by agjohnson** [comment]
This was test with a pretty simple addition:

image

**Review by humitos — APPROVED** [review]
I think this is fine.

However, we will need some extra changes to make this library usable from our script:

- do not auto-execute `setup()` when the module is imported
- export `compare`, which is the function we are using there

See https://github.com/readthedocs/doc-diff/pull/8/ and https://github.com/humitos/readthedocs-client/blob/844f0fa4280e2048b6b13e468c723e9b3b0f75ad/src/docdiff.js#L1-L22 to understand how I'm using it.

`setup()` function does _too much_ for what we need here.

**Comment by agjohnson** [comment]
@humitos I was punting on a few of these changes for now, and didn't look at what was needed for export yet, but I jumped back in on this to iron out the pattern a bit more in [14a8471](https://github.com/readthedocs/doc-diff/pull/9/commits/14a847189cc787f79dda2717a6960fbb6ccb612b)

A couple of notes:

- Instead of just exporting singular functions that we need, our outer-most libraries should be liberal with what they export. In this case, everything in `extension.js` is exported for reuse, instead of just `setup()`/etc.
- There are two files output now. I'm not settled on naming patterns/etc here yet though. It is a bit more confusing, but the summary is that `readthedocs-doc-diff` is a browser module, which will execute automatically. If you are including in another library, you'd use `import * as docDiff from "doc-diff"` to include the module version of this, which is the version that _will not_ automatically execute logic.

**Review by humitos — APPROVED** [review]
Sounds good! We can talk more about the pattern followed here if necessary, but it's fine for now. We will require similar changes on search and ethicalads

**Pull request merged**
