### PR TITLE
Wrap URL request in a CORS proxy

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Comment by ericholscher** [comment]
@agjohnson did you want to push your changes to this branch and get them into the prod version here?

**Comment by agjohnson** [comment]
I can push up my changes, but let's set up something more permanent for the CORs proxy. I'd prefer to not use something set up for WTD here.

**Comment by ericholscher** [comment]
Cool, I can just set up a CORS proxy on our CF account: https://cors.readthedocs.workers.dev/

**Comment by ericholscher** [comment]
Ready to merge! Though we might have already fixed CORS 🤔

**Comment by stsewd** [comment]
> Though we might have already fixed CORS

We haven't changed the CORS headers for any new views, but we could add them for docs pages now.

**Comment by ericholscher** [comment]
Don't believe we need this anymore 🎉

**Comment by stsewd** [comment]
@ericholscher we haven't changed the CORS headers for html files, so the original problem is probably still happening

**Pull request closed without merging**
